src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/asciidoc/ruby/index.adoc
src/main/java/examples/Examples.java
src/main/java/examples/package-info.java
src/main/java/io/vertx/redis/package-info.java

Signed-off-by: Paulo Lopes <paulo@mlopes.net>

added documentation

---

src/main/java/io/vertx/redis/RedisClient.java

make sure that we don't break API within 3.x

ensure api is not broken with 3.x

---

src/main/asciidoc/dataobjects.adoc
src/main/asciidoc/groovy/index.adoc
src/main/asciidoc/java/index.adoc
src/main/asciidoc/js/index.adoc
src/main/asciidoc/ruby/index.adoc
src/main/java/io/vertx/redis/impl/ReplyParser.java
src/test/java/io/vertx/test/redis/RedisIOBTest.java

The condition was inverted, first read then check if data was available

Fixes #38 IndexOutOfBoundException when parsing arrays

---

src/main/generated/io/vertx/rxjava/redis/RedisClient.java
src/main/groovy/io/vertx/groovy/redis/RedisClient.groovy
src/main/java/io/vertx/redis/RedisClient.java
src/main/java/io/vertx/redis/impl/AbstractRedisClient.java
src/main/java/io/vertx/redis/impl/RedisClientImpl.java
src/main/resources/vertx-redis-js/redis_client.js
src/main/resources/vertx-redis/redis_client.rb
src/test/java/io/vertx/test/redis/RedisClientTestBase.java

Fixes #58 
The interface was wrong since redis always returns a multibulk (list of strings) (broken API)

Fixes ClassCastException for SPOP many (it always MULTIBULK not BULK)

---

src/main/java/io/vertx/redis/impl/RedisConnection.java
src/test/java/io/vertx/test/redis/SomeTest.java
src/test/java/io/vertx/test/redis/TestReconnect.java

This branch fixes a few issues dealing with the `RedisConnection` state reported by users. It also simplify a bit the state management of the `RedisConnection`.
@pmlopes, @tsegismont, @cescoffier or any one else please review

Redis fixes

---

src/main/java/io/vertx/redis/RedisTransaction.java
src/main/java/io/vertx/redis/impl/RedisClientImpl.java

fix API typpo, set binary should take Buffer

---

src/main/java/io/vertx/redis/RedisClient.java
src/main/java/io/vertx/redis/RedisTransaction.java
src/main/java/io/vertx/redis/impl/RedisClientImpl.java
src/test/java/io/vertx/test/redis/RedisClientTestBase.java

This addresses my issue #98, implementing & testing the RedisClient::existsMany method.

feature #98: create RedisClient::existsMany method

---

src/main/asciidoc/index.adoc
src/main/java/examples/RedisExamples.java

Signed-off-by: BillyYccc <billy112487983@gmail.com>
See https://github.com/vert-x3/vertx-redis-client/issues/103.

Add documentation of enabling domain socket - fixes #103

---

src/main/java/io/vertx/redis/op/LimitOptions.java
src/main/java/io/vertx/redis/op/MigrateOptions.java
src/main/java/io/vertx/redis/op/RangeLimitOptions.java
src/main/java/io/vertx/redis/op/SortOptions.java

Expose the properties for other languages

#107 Expose the properties for other languages

---

src/main/java/io/vertx/redis/RedisClient.java
src/test/java/io/vertx/test/redis/NullableTest.java

https://github.com/vert-x3/vertx-lang-kotlin/issues/69

Return null when getting a key that does not exist

---

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java

All slot commands

---

src/main/java/io/vertx/redis/client/impl/RedisClient.java

Replace direct call by fail method call
Signed-off-by: aygalinc <colin.aygalinc@gmail.com>

Fix null pointer onException.handle call

---

src/main/java/io/vertx/redis/client/impl/types/IntegerType.java

IntegerType: override Response.toInteger()

---

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java

Fix cluster batching for single key commands (#169)

---

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java

https://github.com/vert-x3/vertx-redis-client/issues/201

Support cluster command on RedisClusterClient. -> master

---

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java

https://github.com/vert-x3/vertx-redis-client/issues/201

Support cluster command on RedisClusterClient.

---

src/main/java/io/vertx/redis/client/impl/ArrayQueue.java
src/test/java/io/vertx/redis/client/impl/ArrayQueueTest.java
src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java

Fixes #213

---

src/main/java/io/vertx/redis/client/impl/RedisConnectionImpl.java
src/test/java/io/vertx/redis/client/test/RedisTest.java

Don't crash if queue is full

---

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/test/java/io/vertx/redis/client/test/RedisPooledTest.java

Fixes #220: proper configure the pool weights

---

src/main/java/io/vertx/redis/client/impl/RedisConnectionImpl.java
src/test/java/io/vertx/test/redis/RedisClientTest.java

Version: 3.9.0 and 4.0.0-SNAPSHOT
There is currently an issue where when a NetSocket is closed, the connection is not evicted from the pool. This is easy to product by enabling client-side timeouts
on the Redis server [https://redis.io/topics/clients#client-timeouts]. Because the connection is not being evicted, the next time it is given out you will see a
`CONNECTION_CLOSED` error when trying to use said conncection.
This fix evicts the connection on `NetScoket` close.
Signed-off-by: dave sinclair <stampy88@yahoo.com>

Evict connection from pool on NetSocket close

---

src/main/java/io/vertx/redis/impl/RedisClientImpl.java
src/test/java/io/vertx/redis/impl/RedisClientImplTest.java

encode the password and test RedisURI for encode password

---

src/main/asciidoc/enums.adoc
src/main/java/io/vertx/redis/client/Response.java
src/main/java/io/vertx/redis/client/ResponseType.java
src/main/java/io/vertx/redis/client/impl/RESPParser.java
src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionImpl.java
src/main/java/io/vertx/redis/client/impl/types/AttributeType.java
src/main/java/io/vertx/redis/client/impl/types/Multi.java
src/main/java/io/vertx/redis/client/impl/types/MultiType.java
src/main/java/io/vertx/redis/client/impl/types/PushType.java
src/test/java/io/vertx/redis/client/impl/ReplyParserTest.java
src/test/java/io/vertx/redis/client/test/RedisPubSubTest.java
src/test/java/io/vertx/test/redis/RedisClientTest.java

Add support for RESP3 with fallback to RESP2

Implement support for RESP3

---

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelConnection.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/test/java/io/vertx/test/redis/RedisClientTest.java

Do not leak connections on sentinel

---

src/test/java/io/vertx/test/redis/RedisClusterClientTest.java

Motivation:
Ensure that we work as expected with password protected clusters.

Cluster password

---

src/main/java/io/vertx/redis/client/Redis.java
src/main/java/io/vertx/redis/client/RedisConnection.java
src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java
src/main/java/io/vertx/redis/client/impl/RedisClient.java
src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelConnection.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/main/java/io/vertx/redis/client/impl/Resolver.java
src/main/java/io/vertx/redis/client/impl/types/MultiType.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
src/test/java/io/vertx/redis/client/test/RedisTest.java
src/test/java/io/vertx/test/redis/RedisThreadConsistencyTest.java

Ensure replies are run on the right context

---

.github/workflows/CI.yml
src/main/java/io/vertx/redis/client/Request.java
src/main/java/io/vertx/redis/client/impl/RequestImpl.java
src/test/java/io/vertx/test/redis/RedisClient5Test.java
src/test/java/io/vertx/test/redis/RedisClient6Test.java
tools/test.js

null is encoded to a string as per redis protocol

---

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java

Motivation:
Fix #274 : The validation was asserting the wrong value

Check total endpoints against the right value

---

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/test/java/io/vertx/test/redis/RedisClientTLSTest.java

log ssl upgrade

---

src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java
src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
src/test/java/io/vertx/redis/client/test/RedisPooledTest.java
src/test/java/io/vertx/redis/client/test/RedisTest.java

Motivation:
https://gitter.im/eclipse-vertx/vertx-users?at=6051bb483a9448256c0f2d8e
Empty batches are never resolved.

Allow empty batch

---

src/main/java/io/vertx/redis/client/RedisOptions.java
src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/test/java/io/vertx/redis/client/test/RedisMetricsTest.java

Initial support for pool metrics

---

src/main/java/io/vertx/redis/client/RedisConnection.java
src/main/java/io/vertx/redis/client/RedisOptions.java
src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java
src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java
src/main/java/io/vertx/redis/client/impl/RedisAPIImpl.java
src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionInternal.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelConnection.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/main/java/io/vertx/redis/client/impl/types/AttributeType.java
src/main/java/io/vertx/redis/client/impl/types/MultiType.java
src/main/java/io/vertx/redis/client/impl/types/PushType.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
src/test/java/io/vertx/redis/client/test/RedisPooledTest.java

Do not reuse connections that enter pubsub mode

---

src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/RedisURI.java
src/main/java/io/vertx/redis/client/impl/Resolver.java
src/test/java/io/vertx/redis/client/test/RedisSentinelWithDBTest.java

Motivation:
Allow the usage of select during connection handshake in sentinel mode.

Fix #302: allow select during sentinel mode

---

src/main/asciidoc/index.adoc
src/main/java/examples/RedisExamples.java
src/main/java/io/vertx/redis/client/Redis.java
src/main/java/io/vertx/redis/client/RedisClientType.java
src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java
src/main/java/io/vertx/redis/client/impl/RedisReplicationConnection.java
src/test/java/io/vertx/redis/client/test/RedisPooledTest.java
src/test/java/io/vertx/redis/client/test/RedisReplicationTest.java

Fixes #298 
This is the initial PR

Fixes #298: Implement replication support

---

src/test/java/io/vertx/test/redis/RedisClient7Test.java
src/test/java/io/vertx/test/redis/RedisClusterClientIT.java

Adding base tests for 7

---

src/test/java/io/vertx/test/redis/RedisClientREJSONTest.java

Motivation:
Simple PoC for discussion, showing that extensions/modules can be used with the client.

ReJSON PoC

---

src/main/java/io/vertx/redis/client/Command.java
src/main/java/io/vertx/redis/client/impl/ArrayQueue.java
src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java
src/main/java/io/vertx/redis/client/impl/CommandImpl.java
src/main/java/io/vertx/redis/client/impl/ParserHandler.java
src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java
src/main/java/io/vertx/redis/client/impl/RESPParser.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionInternal.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/test/java/io/vertx/redis/client/impl/ReplyParserTest.java
src/test/java/io/vertx/redis/client/test/RedisPooledTest.java
src/test/java/io/vertx/redis/client/test/RedisTest.java
src/test/java/io/vertx/test/redis/RedisClient6Test.java
src/test/java/io/vertx/test/redis/RedisClientLoadTest.java

Motivation:
Trying to reproduce/fix broken pipe errors during connect

Improve the client state management, when network is unstable and RST packets trigget network errors

---

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java

fixed NPE with embedded Vert.x where context is not created

---

src/main/java/io/vertx/redis/client/impl/ConnectionManager.java

Signed-off-by: okou19900722 <ilayan19900722@gmail.com>
Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

Compatible with older versions of auth requests that do not require the user parameter

---

src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/main/java/io/vertx/redis/client/impl/RedisReplicationConnection.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/Slots.java

Removing SplittableRandom as it causes trouble compiling to native

---

src/main/java/io/vertx/redis/client/Redis.java
src/main/java/io/vertx/redis/client/RedisAPI.java
src/main/java/io/vertx/redis/client/RedisConnection.java
src/main/java/io/vertx/redis/package-info.java

https://github.com/vert-x3/issues/issues/612

Deprecate callbacks

---

src/main/java/examples/RedisExamples.java

the same as https://github.com/vert-x3/vertx-redis-client/pull/377. backport to 4.x

feat - improve reconnection example code

---

src/main/java/examples/RedisExamples.java

Motivation:
Explain here the context, and why you're making that change, what is the problem you're trying to solve.
Conformance:

feat - remove unneeded close in reconnection

---

src/main/asciidoc/index.adoc
src/main/generated/io/vertx/redis/client/RedisConnectOptionsConverter.java
src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java
src/main/java/examples/RedisExamples.java
src/main/java/io/vertx/redis/client/ProtocolVersion.java
src/main/java/io/vertx/redis/client/RedisConnectOptions.java
src/main/java/io/vertx/redis/client/RedisOptions.java
src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
src/test/java/io/vertx/redis/client/test/RedisProtocolVersionTest.java

[4.x] add configuration option for the preferred protocol version to use during handshake

---

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java

In the cluster, replication and sentinel modes, the first thing we do is iterate through known nodes and for each, connect and send a command to collect some information, until we obtain a successful response.
This commit makes sure we remember the failures and when no successful response is ever obtained, we can complete the connection `Future` with an error message that contains the actual failures and not just a placeholder string.
Backport of #426 to 4.x

[4.x] Remember failures when collecting initial information in cluster/replication/sentinel

---

src/main/java/io/vertx/redis/client/Response.java
src/main/java/io/vertx/redis/client/impl/types/AttributeType.java
src/main/java/io/vertx/redis/client/impl/types/MultiType.java
src/main/java/io/vertx/redis/client/impl/types/PushType.java
src/test/java/io/vertx/redis/client/test/RedisProtocolVersionTest.java

[4.x] Add Response.isArray() and isMap()

---

src/main/java/io/vertx/redis/client/PoolOptions.java
src/main/java/io/vertx/redis/client/RedisOptions.java

[4.x] Improve javadoc of connection pool options

---

src/main/java/io/vertx/redis/client/impl/Slots.java

Since Redis 7.0, the `CLUSTER SLOTS` command is allowed to return `null` or `""` (empty string) as the hostname of a node that serves a given shard. This return value means that the "current" hostname (that was used to connect to the Redis node in order to execute `CLUSTER SLOTS`) should be used (but the port number must still be obtained from the result of `CLUSTER SLOTS`).
See https://redis.io/commands/cluster-slots/ for more info.
The main motivation here is a Quarkus user who reported the issue in Zulip: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Redis.20client.20in.20cluster.20mode.20cannot.20parse.20.28just.29.20port.20number

Fix reading CLUSTER SLOTS when host is null or empty

---

src/main/java/io/vertx/redis/client/impl/Slots.java

[4.x] Fix reading CLUSTER SLOTS when host is null or empty

---

src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java

Fixed correct node selection for CLUSTER batch command

---

src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java

[4.x] 447 cluster batch command same slot calculation is wrong 4.x

---

src/main/java/io/vertx/redis/client/PoolOptions.java
src/main/java/io/vertx/redis/client/RedisOptions.java
src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java
src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
src/test/java/io/vertx/redis/client/impl/ConnectionRecyclingTest.java

- fix connection recycling
- canonicalize fallback URL in the cluster client
- remove useless validations

Improve connection pooling

---

src/main/java/io/vertx/redis/client/RedisCluster.java
src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java
src/main/java/io/vertx/redis/client/impl/RedisClusterImpl.java
src/main/java/io/vertx/redis/client/impl/Slots.java
src/test/java/io/vertx/redis/client/test/RedisClusterTest.java

[4.x] Add Redis cluster utilities

---

src/main/java/io/vertx/redis/client/impl/CommandReporter.java
src/test/java/io/vertx/tests/redis/client/RedisTracingTest.java

See https://github.com/eclipse-vertx/vertx-tracing/issues/69

Use names specified by OpenTelemetry for tags

---

src/test/java/io/vertx/tests/redis/client/RedisPubSubClusterTest.java
src/test/java/io/vertx/tests/redis/client/RedisPubSubTest.java
src/test/java/io/vertx/tests/redis/client/TestUtils.java

fix PubSub tests

---

src/test/java/io/vertx/tests/redis/client/RedisPubSubClusterTest.java
src/test/java/io/vertx/tests/redis/client/RedisPubSubTest.java
src/test/java/io/vertx/tests/redis/client/TestUtils.java

[5.0] fix PubSub tests

---

.github/workflows/ci-4.x.yml
src/test/java/io/vertx/redis/client/test/RedisClientPubSubTest.java
src/test/java/io/vertx/redis/client/test/RedisPubSubTest.java
src/test/java/io/vertx/redis/client/test/TestUtils.java
src/test/java/io/vertx/test/redis/RedisPubSubTest.java

[4.x] fix PubSub tests
