src/main/asciidoc/groovy/index.adoc, src/main/asciidoc/js/index.adoc, src/main/asciidoc/ruby/index.adoc, src/main/java/io/vertx/redis/impl/AbstractRedisClient.java, src/main/java/io/vertx/redis/impl/Command.java, src/main/java/io/vertx/redis/impl/RedisConnection.java, src/main/java/io/vertx/redis/impl/Reply.java, src/main/java/io/vertx/redis/impl/ReplyParser.java, src/main/resources/vertx-redis-js/redis_client.js, src/main/resources/vertx-redis/redis_client.rb, src/test/java/io/vertx/test/redis/RedisClientTestBase.java
Signed-off-by: Paulo Lopes <paulo@mlopes.net>
Fixes:
#5 not really related to the blocking but a bug regading parsing of null arrays.
Implements:
Running of the response handlers on the right context
Minor:
some clean ups based on unused code.
=> fix issue 5 plus some more code clean up

src/main/java/io/vertx/redis/impl/AbstractRedisClient.java
The switch case comparison fails for command as of 3.0.0 since we pass ing upper case commands, but in the switch cases we're using lower case string literals.
=> convert commands to lowercase to compare with switch cases string literals

src/main/java/io/vertx/redis/RedisClient.java, src/main/java/io/vertx/redis/impl/RedisClientImpl.java, src/main/java/io/vertx/redis/op/FailoverOptions.java, src/main/java/io/vertx/redis/op/ResetOptions.java, src/main/java/io/vertx/redis/op/SlotCmd.java, src/main/resources/vertx-redis-js/redis_client.js, src/main/resources/vertx-redis/redis_client.rb, src/test/java/io/vertx/test/redis/RedisClientTestBase.java
Add missing 3.0 API related to clustering, testing however is more complicated since both docker images and embedded redis do not support clustering, still need to figure out how to automate testing for this.
There is nothing really exciting here just add the commands to the client interface and delegate to the generic redis command on the impl.
@purplefox @vietj @cescoffier please review
=> #12 add missing cluster commands

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/enums.adoc, src/main/java/io/vertx/redis/RedisClient.java, src/main/java/io/vertx/redis/impl/RedisClientImpl.java, src/main/resources/vertx-redis-js/redis_client.js, src/main/resources/vertx-redis/redis_client.rb, src/test/java/io/vertx/test/redis/RedisClientTestBase.java
=> Fixes: #50 - setWithOptions does return simple String value

src/main/java/examples/Examples.java, src/main/java/io/vertx/redis/RedisClient.java, src/main/java/io/vertx/redis/impl/RedisClientImpl.java, src/main/java/io/vertx/redis/impl/Reply.java, src/test/java/io/vertx/test/redis/RedisClientTestBase.java
The issue #52 was that all the commands in Redis MULTI will return a string as "QUEUED" or syntax error if any(src: navigate to "Errors inside a Transaction" in this [site](http://redis.io/topics/transactions) ) . So while using hgetall inside transaction, it was trying to cast String - "QUEUED" to JsonObject which generated the CastException. I have implemented Transaction as an entity. Here is an [example-code](https://github.com/Ashwin-Surana/vertx-redis-client/blob/transaction-implementation/src/main/java/examples/Examples.java) on how to use this transaction entity (Check example5() method). This fix was achieved by removing multi, exec, discard, watch and unwatch methods from RedisClient and making them available in [RedisTransaction](https://github.com/Ashwin-Surana/vertx-redis-clie …
=> Fix for issue #52 ( java.lang.ClassCastException, While using hgetall in a transaction)

pom.xml
Added bnd configuration to all auth providers to generate OSGi manifests. Test cases are available in a Bndtools workspace here: https://github.com/paulbakker/vertx-osgi-testcases/tree/master
Note that this requires the unreleased bnd-maven-plugin 3.2 plugin.
=> bnd config to generate OSGi metadata

src/main/java/examples/Examples.java, src/main/java/io/vertx/redis/RedisClient.java, src/main/java/io/vertx/redis/Script.java, src/main/java/io/vertx/redis/impl/RedisClientImpl.java, src/main/java/io/vertx/redis/impl/ScriptImpl.java, src/test/java/io/vertx/test/redis/EvalTest.java
Adds the method `evalScript` to `RedisClient`. 
This is not a Redis command, rather a higher level function that can be used to evaluate a script on Redis without worrying about script caching. It is modelled after [defineCommand in luin/ioredis](https://github.com/luin/ioredis#lua-scripting), and basically serves as a replacement for `eval`.
When calling `evalScript` it executes EVALSHA, and if the server responds with NOSCRIPT error, it tries again using EVAL. (This makes it impossible to do in a transaction).
See [Bandwith and EVALSHA](https://redis.io/commands/eval#bandwidth-and-evalsha)
=> Add high level scripting method

src/main/java/io/vertx/redis/RedisOptions.java
Copypasta on setBinary, and misspelled "correlation"
=> Fix copy/paste typo in javadoc

src/main/java/io/vertx/redis/RedisClient.java, src/main/java/io/vertx/redis/RedisTransaction.java, src/main/java/io/vertx/redis/impl/RedisClientImpl.java, src/main/java/io/vertx/redis/impl/RedisCommand.java
It seems that the client presently doesn't support the new command 'UNLINK' and 'SWAPDB' since Redis 4.0.0, I spend some time to make it work:)
=> Add Support for Command 'UNLINK' and 'SWAPDB'

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/enums.adoc, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/examples/RedisExamples.java, src/main/java/io/vertx/redis/client/Redis.java, src/main/java/io/vertx/redis/client/RedisClientType.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/RedisClient.java, src/main/java/io/vertx/redis/impl/RedisSentinelClientImpl.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java
This will allow instances of redis clients to be configurable instead of hard coded.
=> Use a single factory

src/main/java/io/vertx/redis/client/RedisException.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/types/ErrorType.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
This is PR related to issue #158 
The fixes proposed are:
1. In RedisClusterClient check ErrorType instead of RedisException
1. Adding slice method in ErrorType
1. Mark RedisException @Depecrated because is not used in client code
1. Modified RedisClusterClientTest to test this behavior
=> fixes #158 Cluster Client error handling fix proposal

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java
This is PR related to issue #160
Following discussion on Gitter between @damianofontana85 and @pmlopes I have implemented a possible solution for the related issue. The redis cluster client sends READONLY command if the slave mode is ALWAYS or SHARE to slave nodes at connection time.
=> fixes #160 Cluster Client send READONLY command on connection proposal

src/main/java/io/vertx/redis/client/impl/ConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionImpl.java
1.Recycle timeout is relative to currentTimeMillis
2.Actually close the connection when asked from pool
=> Fixes #189

src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/examples/RedisExamples.java, src/main/java/io/vertx/redis/client/Redis.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/ConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisURI.java, src/test/java/io/vertx/redis/client/impl/RedisURITest.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java, src/test/java/io/vertx/redis/client/test/RedisTest.java, src/test/java/io/vertx/test/redis/RedisClientTest.java
Added Redis URI support according to IANA spec for the issue: https://github.com/vert-x3/vertx-redis-client/issues/183
Overall, the changes are minimalistic: fixed support of password extraction from the uri (as it's a common thing not to have a username in this kind of strings).
The overall schema can be found at https://www.iana.org/assignments/uri-schemes/prov/redis as pointed by @pmlopes 
In a separate commit, replaces `addEndpoint` calls with `addConnectionString` which does the same thing but highlights that a connection URI can be passed as a param. This change might be reverted if needed.
=> Add redis URI support according to IANA

src/main/java/io/vertx/redis/client/impl/KeyExtractor.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/test/java/io/vertx/redis/client/impl/KeyExtractorTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
https://github.com/vert-x3/vertx-redis-client/issues/198
- Extraction of the keys on movable key commands.
- Validation of those keys that they target the same hash slot.
- Normalization of hash slot issue related exception messages.
- Consider commands (currently only WAIT) they must be run against master nodes.
=> Support for movable keys commands on clustered Redis client (send and batch)

src/main/java/io/vertx/redis/client/impl/KeyExtractor.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/Slots.java, src/test/java/io/vertx/redis/client/impl/KeyExtractorTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
https://github.com/vert-x3/vertx-redis-client/issues/198
- Extraction of the keys on movable key commands.
- Validation of those keys that they target the same hash slot.
- Normalization of hash slot issue related exception messages.
- Consider commands (currently only WAIT) they must be run against master nodes.
- Fix for batch if the first command is a single key command.
=> Support for movable keys commands on clustered Redis client (send and batch) -> master

src/main/java/examples/RedisExamples.java
Motivation:
I wanted to apply an exponential backoff mechanism for Redis reconnection from the docs (https://vertx.io/docs/vertx-redis-client/java/#_implementing_reconnect_on_error) and found, that there is a bug in it: instead of increasing the timeout up to some limit, it constantly returned the same number: 20, due to a mistake in the `pow` argument.
I applied similar logic that increases the timeouts as next:
```20, 40, 80, 160, 320, 640, 1280, 2560, 5120, 10240, 10240, 10240, 10240, 10240, 10240, 10240, 10240, 10240, 10240, 10240```
I haven't added a proper test case, as it's just an example, but here is a simple test that you can run to visualise the new or old algorithm:
It's on Junit5, but you can run it as a main function as well.
``` 
@Test
void printBackoffValues() {
int …
```
=> Fix an issue in Example. Backoff calculations led to constant backoff timing

src/main/asciidoc/dataobjects.adoc, src/main/asciidoc/enums.adoc, src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/io/vertx/redis/client/RedisClientType.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/RedisReplicas.java, src/main/java/io/vertx/redis/client/RedisRole.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/Slots.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java
Motivation:
Words such as `slave` are offensive but were common on distributed system naming conventions. Redis has started changing the way nodes on a cluster are named for a long period, with a first official release with redis 5.
This PR is following up on their work and adapting the client wording to the official redis convention.
=> Clean up wording, regarding slavery

src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java, src/main/java/io/vertx/redis/client/impl/RedisClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/main/java/io/vertx/redis/client/impl/Resolver.java, src/test/java/io/vertx/redis/client/test/RedisPooledTest.java
core connection pool API changed, this PR uses the latest API + removed the usage of `runOnContext`
=> Upgrade to the latest core API and avoid runOnContext

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
Motivation:
attempting to fix the "bug" described in https://github.com/vert-x3/vertx-redis-client/issues/264
=> BUG-264 updating the connection pool creation for the redis client

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java
Motivation:
I'm receiving null pointer exceptions (see below) when trying to reconnect with redis in a kubernetes cluster. These errors propogate as unhandled.
```json
{
"timestamp": 1607029901178,
"log": {
"instant": {
"epochSecond": 1607029901,
"nanoOfSecond": 177546000
},
"thread": "vert.x-eventloop-thread-0",
"level": "ERROR",
"loggerName": "io.vertx.core.impl.ContextImpl",
"message": "Unhandled exception",
"thrown": {
"commonElementCount": 0,
"name": "java.lang.NullPointerException",
"extendedStackTrace": [
{
"class": "io.vertx.redis.client.impl.RedisConnectionManager$RedisConnectionProvider",
"method": "lambda$hello$6",
"file": "RedisConnectionManager.java",
"line": 214,
"exact": false,
"location": "service.jar",
"version": "?"
},
{
"class": "io.vertx.core.impl.future.FutureImpl$3", …
```
=> Fix NPE when handling errors during "hello" negotiation.

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisURI.java, src/main/java/io/vertx/redis/client/impl/Slots.java, src/test/java/io/vertx/redis/client/impl/RedisURITest.java, src/test/java/io/vertx/redis/client/impl/SlotsTest.java
Motivation:
When connecting to a redis cluster, the client now propagates username
and password from the initial connection to each of the cluster
member connections.
This is a back port of changes to `RedisURI` and `Slots` from the master branch.
Closes #270  
Conformance:
=> Backport redis cluster authentication changes

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/test/java/io/vertx/test/redis/RedisClientPikaTest.java
Motivation:
Add support for pikadb
pikadb return is somehow different from redis regarding unknown commands. This fails the validation of the connection handshake.
=> Add support for pikadb

src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java
Currently, when a connection [is returned to the pool](https://github.com/eclipse-vertx/vert.x/blob/358cee178d9e1754ae57b5f8e95b605a74be22d6/src/main/java/io/vertx/core/net/impl/clientconnection/Pool.java#L304), the validation is always `false` due to the `expirationTimestamp` in `RedisStandaloneConnection` is always 0.
The `recycle` function indicates that if the `expirationTimestamp` should be 0 if we don't want to recycle, therefore, I changed the `isValid()`. However, since `recycle()` is never called, and this client uses a timer to close connections, I wonder it might be better to remove `expirationTimestamp`, `recycle()`, and always return `true` in `isValid()`.
=> Fix wrong connection validation

src/main/java/io/vertx/redis/client/RedisConnection.java
Motivation:
Adds a missing Nullable annotation. I think this is the cause of an "io.vertx.codegen.GenException: Nullable type cannot override non nullable" that I am experiencing when compiling Vert.x modules with a vertx-codegen CodegenProcessor.
I believe that this annotation should be present because it is there on the corresponding method in [ReadStream](https://github.com/eclipse-vertx/vert.x/blob/4.1.0/src/main/java/io/vertx/core/streams/ReadStream.java#L62).
=> Add a missing Nullable annotation

src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/test/java/io/vertx/redis/client/impl/ReplyParserTest.java, src/test/java/io/vertx/test/redis/RedisClientIT.java
Motivation:
Azure redis hello response is broken. This means we can't rely on it to perform the protocol negotiation and avoid it completely.
https://docs.microsoft.com/en-us/answers/questions/431238/azure-redis-603-responding-incorrectly-to-hello-3.html
This PR introduces a new option flag to not use hello during handshake to properly work around this limitation.
=> Azure redis hello command is broken, we need to avoid it

src/main/java/io/vertx/redis/client/impl/ConnectionManager.java, src/test/java/io/vertx/redis/impl/RedisClientImplTest.java
ConnectionManager should also have in consideration the username parsed from RedisURI: 
https://github.com/vert-x3/vertx-redis-client/blob/dc2147d76ae3078ae9687ec4789029eac632fee9/src/main/java/io/vertx/redis/client/impl/ConnectionManager.java#L126
Motivation:
Fix for https://github.com/vert-x3/vertx-redis-client/issues/315
=> Pass user to auth Redis command

src/main/java/io/vertx/redis/client/impl/RedisURI.java, src/test/java/io/vertx/redis/client/impl/RedisURITest.java
Motivation:
userinfo needs to be processed in raw mode, so we can clearly identify the colon that splits user from password.
=> Fix #322: correctly handle the uri userinfo

src/main/java/io/vertx/redis/client/Response.java, src/main/java/io/vertx/redis/client/impl/ReadableBuffer.java, src/test/java/io/vertx/test/redis/RedisClient7Test.java
Motivation:
To handle a few extensions and in preparation to `nan` support in RESP3 protocol this PR will support both native `nan` and String base `nan`
=> Adding support for special doubles

src/main/java/io/vertx/redis/client/impl/CommandImpl.java, src/main/java/io/vertx/redis/client/impl/RequestImpl.java, tools/package.json
Motivation:
Connection pool builds a key based on connection url and setup command, this PR adds equals and hashcode implementation to objects that are used to compose that key to avoid uneeded generation of connections.
=> Adding equals/hashcode to members that compose key for connection pool

src/main/java/examples/RedisExamples.java
Motivation:
- fix the connection leak in reconnect example code mentioned in https://github.com/vert-x3/vertx-redis-client/pull/292#issuecomment-1122513218 
- improve reconnection example code with `endHandler` as described in https://github.com/vert-x3/vertx-redis-client/issues/375
=> feat - improve reconnection example code

src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
Motivation:
There are normal cases for `mget` command in clustered redis that will fail to execute with vert.x redis client
Conformance:
=> fix: mget with multiple keys in different slots but first two in the same slot will fail

src/main/generated/io/vertx/redis/client/PoolOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisClusterConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisSentinelConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisStandaloneConnectOptionsConverter.java, src/main/java/io/vertx/redis/client/PoolOptions.java, src/main/java/io/vertx/redis/client/Redis.java, src/main/java/io/vertx/redis/client/RedisClusterConnectOptions.java, src/main/java/io/vertx/redis/client/RedisConnectOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/RedisSentinelConnectOptions.java, src/main/java/io/vertx/redis/client/RedisStandaloneConnectOptions.java, src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java, src/main/java/io/vertx/redis/client/impl/RedisClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationConnection.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/main/java/io/vertx/redis/client/impl/Resolver.java
Current `RedisOptions` mix connect and pooling options in the same class. If we want to use an options supplier pattern we should distinguish between those.
This PR decompose the `RedisOptions` in `PoolOptions` and a `RedisConnectOptions` hierarchy (for various client types) and keep the `RedisOptions` possible.
=> Options decomposition

src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/examples/RedisExamples.java, src/main/java/io/vertx/redis/client/Redis.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java, src/main/java/io/vertx/redis/client/impl/CommandReporter.java, src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java, src/main/java/io/vertx/redis/client/impl/RedisClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionInternal.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationConnection.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelConnection.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/test/java/io/vertx/redis/client/test/PreservesContext.java, src/test/java/io/vertx/redis/client/test/RedisClientMetricsTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisPoolMetricsTest.java, src/test/java/io/vertx/redis/client/test/RedisReplicationTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java, src/test/java/io/vertx/redis/client/test/RedisTest.java, src/test/java/io/vertx/redis/client/test/RedisTracingTest.java
Motivation:
- make sure that the Redis client calls back on the original context
- this used to be the case for the clustered clients, but nor for the standalone client, which is fixed here
- make connection pooling explicit in the code
- the internal structure of connection handling is more obvious by using the `PooledRedisConnection` type explicitly
- this even revealed a bug in `RedisSentinelClient` which would lead to class cast errors in some failure scenarios
- implement tracing and client metrics
- this is done similarly to how the Vert.x SQL client does it, which is a little less precise, but easier to understand
Resolves #357
=> Implement tracing and client metrics

src/main/java/io/vertx/redis/client/impl/CommandImpl.java, src/main/java/io/vertx/redis/client/impl/RequestImpl.java, tools/package.json
Backport of #374 to 4.x. Without this, connection pooling basically doesn't work.
=> [4.x] Adding equals/hashcode to members that compose key for connection pool

src/main/java/io/vertx/redis/client/RedisOptions.java, src/test/java/io/vertx/redis/client/test/RedisOptionsTest.java
Motivation:
I kept running into `Redis waiting Queue is full` exceptions. After debugging, I found that when I copied the options during my setup, the `maxWaitingHandlers` was not copied and therefore got set to `0`.
Looks like this was inadvertently dropped when the options were decomposed into specific pool/connect options:
https://github.com/vert-x3/vertx-redis-client/pull/395/files#diff-c7335b2f2f7228ced4e9f5842327edab03b17586a270d7479f15df7eeb50f334L95
Conformance:
=> fix RedisOptions copy constructor

src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisClusterConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/examples/RedisExamples.java, src/main/java/io/vertx/redis/client/RedisClusterConnectOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
=> [4.x] Fix how hash slot assignment is retrieved and stored

src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisClusterConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/examples/RedisExamples.java, src/main/java/io/vertx/redis/client/RedisClusterConnectOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
Previously, the `RedisClusterClient` used to obtain the hash slot
assignment as the first step of each `connect()` call. This is fairly
expensive and increases the load on the first endpoint in the list
(because we target the first endpoint when issuing `CLUSTER SLOTS`).
It is also unnecessary. Redis always sends a redirection when the node
to which a command is sent is not assigned the hash slot targetted
by the command. Until we observe such redirection, the hash slot
assignment we observed before is still valid. Hence, we can store
the hash slot assignment in the `RedisClusterClient` and reuse it
for all `RedisClusterConnection` objects, until the `MOVED` error
is seen. In such case, we reset the hash slot assignment so that
the next `connect()` call fetches it again.
To avoid spurious …
=> Fix how hash slot assignment is retrieved and stored

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/test/java/io/vertx/redis/client/test/RedisTest.java, src/test/java/io/vertx/redis/client/test/SharedRedisConnectionTest.java, src/test/java/io/vertx/test/redis/RedisClientTLSTest.java
When a single `RedisConnection` is shared among multiple contexts (e.g. verticles), pipelining doesn't work correctly, because there is no coordination for concurrent access. This commit fixes that by making sure that all requests are performed from the same context on which the `NetSocket` was created. If the current context is different from the `NetSocket` context, the request is emitted on the correct context, which means no concurrent access, all requests are serialized.
Fixes #394
=> fix Redis connection sharing

src/main/java/io/vertx/redis/client/impl/RedisConnectionManager.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/test/java/io/vertx/redis/client/test/RedisTest.java, src/test/java/io/vertx/redis/client/test/SharedRedisConnectionTest.java, src/test/java/io/vertx/test/redis/RedisClientTLSTest.java
When a single `RedisConnection` is shared among multiple contexts (e.g. verticles), pipelining doesn't work correctly, because there is no coordination for concurrent access. This commit fixes that by making sure that all requests are performed from the same context on which the `NetSocket` was created. If the current context is different from the `NetSocket` context, the request is emitted on the correct context, which means no concurrent access, all requests are serialized.
Backport of #421 to 4.x
=> [4.x] fix Redis connection sharing

src/main/java/io/vertx/redis/client/Command.java, src/main/java/io/vertx/redis/client/RedisAPI.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisConnectException.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationConnection.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/main/java/io/vertx/redis/client/impl/Slots.java, src/test/java/io/vertx/redis/client/CommandGenerator.java, tools/commands.js, tools/package.json, tools/redis-api.hbs
Several commits, best reviewed in isolation:
- show all errors when connecting to Redis cluster fails
- use a subclass of ConnectException on connection failure in cluster/replication client
- fix caching of hash slot assignment in cluster client
- improve some code comments slightly
- treat sharded pub/sub commands as pub/sub commands
- improve how documentation links are generated in RedisAPI
=> Redis cluster improvements

src/main/java/io/vertx/redis/client/Command.java, src/main/java/io/vertx/redis/client/RedisAPI.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisConnectException.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationConnection.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/main/java/io/vertx/redis/client/impl/Slots.java, src/test/java/io/vertx/redis/client/CommandGenerator.java, tools/commands.js, tools/package.json, tools/redis-api.hbs
Several commits, best reviewed in isolation:
- show all errors when connecting to Redis cluster fails
- use a subclass of ConnectException on connection failure in cluster/replication client
- fix caching of hash slot assignment in cluster client
- improve some code comments slightly
- treat sharded pub/sub commands as pub/sub commands
- improve how documentation links are generated in RedisAPI
Backport of #419 to 4.x.
=> [4.x] Redis cluster improvements

src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java
In the cluster, replication and sentinel modes, the first thing we do is iterate through known nodes and for each, connect and send a command to collect some information, until we obtain a successful response.
This commit makes sure we remember the failures and when no successful response is ever obtained, we can complete the connection `Future` with an error message that contains the actual failures and not just a placeholder string.
=> Remember failures when collecting initial information in cluster/replication/sentinel

src/main/java/io/vertx/redis/client/Response.java, src/main/java/io/vertx/redis/client/impl/types/AttributeType.java, src/main/java/io/vertx/redis/client/impl/types/MultiType.java, src/main/java/io/vertx/redis/client/impl/types/PushType.java, src/test/java/io/vertx/redis/client/test/RedisProtocolVersionTest.java
This makes working with responses of type `ResponseType.MULTI`, `PUSH` and `ATTRIBUTE` a bit easier.
Fixes #342
=> Add Response.isArray() and isMap()

src/main/java/io/vertx/redis/client/PoolOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java
=> Improve javadoc of connection pool options

src/main/generated/io/vertx/redis/client/RedisConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/io/vertx/redis/client/RedisClusterConnectOptions.java, src/main/java/io/vertx/redis/client/RedisConnectOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/RedisSentinelConnectOptions.java, src/main/java/io/vertx/redis/client/RedisStandaloneConnectOptions.java, src/test/java/io/vertx/redis/client/test/RedisConnectOptionsTest.java, src/test/java/io/vertx/redis/client/test/RedisOptionsTest.java
This commit makes sure that:
- all mandatory fields of `RedisOptions` are initialized (initializing them only in `Redis[*]ConnectOptions` is not enough due to the usage of copy constructors);
- all constructors of subclasses of `RedisConnectOptions` properly delegate to the corresponding superclass constructors;
- the `JsonObject`-accepting constructors of subclasses of `RedisConnectOptions` call the correct conversion function, after delegating to the corresponding superclass constructor, which calls its own conversion function;
- no information is lost during JSON serialization / deserialization, by reordering the getters / setters in the `Redis[Connect]Options` classes.
=> Fix initialization of RedisOptions and Redis[*]ConnectOptions

src/main/java/io/vertx/redis/client/RedisClusterConnectOptions.java, src/main/java/io/vertx/redis/client/RedisConnectOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/RedisSentinelConnectOptions.java, src/main/java/io/vertx/redis/client/RedisStandaloneConnectOptions.java, src/test/java/io/vertx/redis/client/test/RedisConnectOptionsTest.java, src/test/java/io/vertx/redis/client/test/RedisOptionsTest.java
This commit makes sure that:
- all mandatory fields of `RedisOptions` are initialized (initializing them only in `Redis[*]ConnectOptions` is not enough due to the usage of copy constructors);
- all constructors of subclasses of `RedisConnectOptions` properly delegate to the corresponding superclass constructors;
- the `JsonObject`-accepting constructors of subclasses of `RedisConnectOptions` call the correct conversion function, after delegating to the corresponding superclass constructor, which calls its own conversion function.
Backport of #428 to 4.x
=> [4.x] Fix initialization of RedisOptions and Redis[*]ConnectOptions

src/main/java/io/vertx/redis/client/impl/CommandReporter.java, src/main/java/io/vertx/redis/client/impl/RedisConnectionInternal.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/test/java/io/vertx/redis/client/test/RedisTracingTest.java
Add more properties to CommandReporter so we are able to add Server and Network attributes for OpenTelemetry tracing.
Closes https://github.com/vert-x3/vertx-redis-client/issues/441
=> Add more properties to CommandReporter

src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisReplicationTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelWithDBTest.java, src/test/java/io/vertx/test/redis/RedisPubSubTest.java
When starting sentinel, the Grokzen image runs `redis-sentinel`, which is the default installation from the base image and not the built binary. This workaround rewrites the `docker-entrypoint.sh` script to use the built binary of `redis-sentinel`, which doesn't exhibit an issue.
=> workaround a bug in the Grokzen Docker image

src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisReplicationTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelWithDBTest.java, src/test/java/io/vertx/test/redis/RedisPubSubTest.java
When starting sentinel, the Grokzen image runs `redis-sentinel`, which is the default installation from the base image and not the built binary. This workaround rewrites the `docker-entrypoint.sh` script to use the built binary of `redis-sentinel`, which doesn't exhibit an issue.
=> [4.x] workaround a bug in the Grokzen Docker image

src/main/generated/io/vertx/redis/client/RedisConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/io/vertx/redis/client/RedisConnectOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java
The `RedisOptions` class has a field `endpoints` of type `List<String>` for which multiple accessors and mutators exist:
- `getEndpoints()`: the canonical getter
- `setEndpoints()`: the canonical setter
- `getEndpoint()`: returns the first element of the list
- `setEndpoint()`: turns the list into a single-element list
- `addEndpoint()`: adds one element to the list
- `setConnectionString()`: same as `setEndpoint()`
- `addConnectionString()`: same as `addEndpoint()`
The `RedisConnectOptions` class, which is `public` but is only used internally, has the same problem.
All these methods are treated as individual properties by the code generator that produces the JSON serialization/deserialization classes, even though they are all backed by a single field. Since the code generator considers …
=> @GenIgnore non-canonical getters/setters of Redis[Connect]Options.endpoints

src/main/java/io/vertx/redis/client/PoolOptions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisReplicationClient.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/RedisStandaloneConnection.java, src/test/java/io/vertx/redis/client/impl/ConnectionRecyclingTest.java
- fix connection recycling
- canonicalize fallback URL in the cluster client
- remove useless validations
Backport of #456 to 4.x
Fixes #415
=> [4.x] Improve connection pooling

src/main/generated/io/vertx/redis/client/PoolOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisClusterConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisReplicationConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisSentinelConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisStandaloneConnectOptionsConverter.java
This is to bring the generated converters up to date with the latest changes in Vert.x codegen. This doesn't happen automatically, because with the latest Vert.x 5 parent, codegen puts its output no longer into `src/main/generated`, but into `target/generated-source`.
=> Regenerate converters

src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisSentinelConnectOptionsConverter.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/RedisSentinelConnectOptions.java, src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelConnection.java, src/main/java/io/vertx/redis/client/impl/RedisURI.java, src/main/java/io/vertx/redis/client/impl/SentinelFailover.java, src/main/java/io/vertx/redis/client/impl/SharedSlots.java, src/test/java/io/vertx/redis/client/test/ClusterUtils.java, src/test/java/io/vertx/redis/client/test/RedisClusterAskTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterMovedTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterMovedToNewNodeTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelMasterFailoverTest.java, src/test/java/io/vertx/redis/client/test/TestUtils.java, src/test/java/io/vertx/redis/containers/RedisCluster.java
Fixes #320
Fixes #372
Related to #303
This will also fix the following Quarkus issue: https://github.com/quarkusio/quarkus/issues/40151
=> Cluster and sentinel improvements

src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisSentinelConnectOptionsConverter.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/RedisSentinelConnectOptions.java, src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java, src/main/java/io/vertx/redis/client/impl/RedisClusterClient.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelClient.java, src/main/java/io/vertx/redis/client/impl/RedisSentinelConnection.java, src/main/java/io/vertx/redis/client/impl/RedisURI.java, src/main/java/io/vertx/redis/client/impl/SentinelFailover.java, src/main/java/io/vertx/redis/client/impl/SharedSlots.java, src/test/java/io/vertx/redis/client/test/ClusterUtils.java, src/test/java/io/vertx/redis/client/test/RedisClusterAskTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterMovedTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterMovedToNewNodeTest.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java, src/test/java/io/vertx/redis/client/test/RedisSentinelMasterFailoverTest.java, src/test/java/io/vertx/redis/client/test/TestUtils.java, src/test/java/io/vertx/redis/containers/RedisCluster.java
=> [4.x] Cluster and sentinel improvements

src/main/java/io/vertx/redis/client/RedisCluster.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/main/java/io/vertx/redis/client/impl/RedisClusterImpl.java, src/main/java/io/vertx/redis/client/impl/Slots.java, src/test/java/io/vertx/redis/client/test/RedisClusterTest.java
The `RedisCluster` interface exposes several useful operations that only make sense in the context of a cluster:
- run a command against all nodes in the cluster
- run a command against all _master_ nodes in the cluster
- group commands such that each group is guaranteed to be executed on the same node
Fixes #450
Closes #418
=> Add Redis cluster utilities

src/test/java/io/vertx/redis/client/test/PreservesContext.java
The change to add a parameter to this method was reverted, so this commit reverts the previous change as well.
=> [4.x] Adapt to latest change in ContextInternal.current()

src/main/asciidoc/index.adoc, src/main/java/io/vertx/redis/client/EventBusHandler.java, src/test/java/io/vertx/tests/redis/client/RedisPubSubTest.java
When we extracted the Redis subscription -> Vert.x event bus handler, we made a breaking change in how we transfer the `pmessage` messages to the event bus: instead of the original `<prefix>.<pattern>` address, we used `<prefix>.<channel>`. This commit moves the address back.
In addition to that, this commit also fixes the `RedisPubSubTest` to also account for `[p]subscribe` messages.
=> fix the EventBusHandler

src/main/asciidoc/index.adoc, src/main/java/io/vertx/redis/client/Command.java, src/main/java/io/vertx/redis/client/RedisCluster.java, src/main/java/io/vertx/redis/client/Request.java, src/main/java/io/vertx/redis/client/RequestGrouping.java, src/main/java/io/vertx/redis/client/Response.java, src/main/java/io/vertx/redis/client/impl/RedisClusterImpl.java, src/test/java/io/vertx/tests/redis/client/RedisClusterTest.java
- Make `Request`, `Response` and `Command` data objects
- Change `groupByNodes` return type and make `RedisCluter` `@VertxGen`
- Add documentation for `RedisCluster`
=> Improve Redis cluster

src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java, src/test/java/io/vertx/tests/redis/client/RedisPoolMetricsTest.java
In case of a tainted connection, the metrics were not ended properly. This commit fixes that while retaining idempotency of `PooledRedisConnection.close()`.
Fixes #488
=> fix pool metrics for tainted connections

src/main/java/io/vertx/redis/client/impl/PooledRedisConnection.java, src/test/java/io/vertx/redis/client/test/RedisPoolMetricsTest.java
In case of a tainted connection, the metrics were not ended properly. This commit fixes that while retaining idempotency of `PooledRedisConnection.close()`.
Backport of #489 to `4.x`
=> [4.x] fix pool metrics for tainted connections

src/main/java/io/vertx/redis/client/impl/RedisURI.java, src/test/java/io/vertx/tests/redis/internal/RedisURITest.java
The `io.vertx.redis.client.impl.RedisURI` class parsed URIs with only a username in the URI userinfo component but silently dropped it afterwards.
`redis://my-user@example.com:6379/0` was accepted without throwing an exception but the user defaulted to `default` or alternatively to the given `user` query parameter.
This change set modifies the behavior so that the username from the example URI above (`my-user`) is being properly used and that the password is still unset.
Please note that `redis://my-user@example.com` (password is unset/null) and `redis://my-user:@example.com` (password is empty string) are different and both cover valid connection cases.
Additionally the Javadoc for `RedisURI` has been extended to cover the valid URI schems and query parameters.
=> Allow using only a username in Redis URL authinfo

.github/workflows/ci-4.x.yml, src/main/asciidoc/index.adoc, src/main/generated/io/vertx/redis/client/RedisClusterConnectOptionsConverter.java, src/main/generated/io/vertx/redis/client/RedisOptionsConverter.java, src/main/java/examples/RedisExamples.java, src/main/java/io/vertx/redis/client/RedisClientType.java, src/main/java/io/vertx/redis/client/RedisClusterConnectOptions.java, src/main/java/io/vertx/redis/client/RedisClusterTransactions.java, src/main/java/io/vertx/redis/client/RedisOptions.java, src/main/java/io/vertx/redis/client/impl/BaseRedisClient.java, src/main/java/io/vertx/redis/client/impl/CommandImpl.java, src/main/java/io/vertx/redis/client/impl/RedisClusterConnection.java, src/test/java/io/vertx/redis/client/test/Pair.java, src/test/java/io/vertx/redis/client/test/RedisClusterTransactionsTest.java
Backport of #479 to 4.x as agreed in https://github.com/quarkusio/quarkus/issues/32361.
=> [4.x] initial support for single-node Redis transactions in cluster

src/main/java/io/vertx/redis/client/impl/types/MultiType.java, src/test/java/io/vertx/redis/client/impl/ConnectionRecyclingTest.java
=> [4.x] avoid NPE in MultiType.toString()
